// Redirect server for the old docs.re.video site. Every request is looked up in
// redirects.json (generated by build-map.mjs) and answered with a 301 to the
// matching page under https://midrender.com/revideo/docs. Unknown paths fall
// back to the docs home.
//
// Zero dependencies: runs the same under `node src/server.mjs` or
// `bun src/server.mjs`.

import {readFileSync} from 'node:fs';
import {createServer} from 'node:http';
import {dirname, join} from 'node:path';
import {fileURLToPath} from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const redirects = JSON.parse(
  readFileSync(join(here, 'redirects.json'), 'utf8'),
);

const PORT = process.env.PORT || 8080;
const HOME = 'https://midrender.com/revideo/docs';

/** Normalize an incoming path so it matches the map keys (no trailing slash). */
function normalize(pathname) {
  let p = pathname;
  try {
    p = decodeURIComponent(pathname);
  } catch {
    // Malformed percent-encoding: fall back to the raw value.
  }
  if (p.length > 1 && p.endsWith('/')) p = p.replace(/\/+$/, '');
  return p || '/';
}

const server = createServer((req, res) => {
  const url = new URL(req.url, 'http://localhost');
  const path = normalize(url.pathname);

  // Health check for load balancers / uptime probes.
  if (path === '/healthz') {
    res.writeHead(200, {'content-type': 'text/plain'});
    res.end('ok');
    return;
  }

  const exact = redirects[path];
  if (exact) {
    // Preserve the query string; the fragment (#...) is never sent to the server
    // and is retained by the browser automatically.
    res.writeHead(301, {
      location: exact + url.search,
      'cache-control': 'public, max-age=86400',
    });
    res.end();
    return;
  }

  // Unknown path: closest guess is the docs home. Use 302 so we don't
  // permanently cache a guess for a URL we didn't explicitly map.
  res.writeHead(302, {location: HOME + url.search});
  res.end();
});

server.listen(PORT, () => {
  console.log(
    `docs-redirect listening on :${PORT} (${Object.keys(redirects).length} routes)`,
  );
});
